### ISSUE TITLE
Cannot Install

### ISSUE THREAD

**Issue by pirica** [Fortnite-API/php-wrapper#4]
I have proc_open disable on my hosting, any ideas ?

$ composer require fortnite-api/php-wrapper

Using version ^1.0 for fortnite-api/php-wrapper
./composer.json has been updated
Running composer update fortnite-api/php-wrapper
Loading composer repositories with package information
Updating dependencies
Your requirements could not be resolved to an installable set of packages.

  Problem 1
    - Root composer.json requires fortnite-api/php-wrapper ^1.0 -> satisfiable by fortnite-api/php-wrapper[v1.0.0].
    - fortnite-api/php-wrapper v1.0.0 requires guzzlehttp/guzzle ^6.4 -> found guzzlehttp/guzzle[6.4.0, ..., 6.5.5] but it conflicts with your root composer.json require (^7.3).

Use the option --with-all-dependencies (-W) to allow upgrades, downgrades and removals for packages currently locked to specific versions.

Installation failed, reverting ./composer.json and ./composer.lock to their original content.

**Comment by michel-pi** [comment]
i am sorry but this repository isn't up 2 date and therefore can't be used

**Comment by pirica** [comment]
> i am sorry but this repository isn't up 2 date and therefore can't be used

Many thanks!
